version: '3.7'

services:
  postgres:
    image: sanarisan/job_sniper_postgres:1
    restart: always
    build:
      context: ./
      dockerfile: ./docker/postgres.Dockerfile
      shm_size: 512mb
    shm_size: 512mb
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE_NAME}'
    networks:
      - default
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    ports:
      - '${DB_PORT_PROD}:5432'
  app:
    image: sanarisan/job-sniper:1
    restart: always
    build:
      context: ./
      dockerfile: ./docker/app.Dockerfile
    stop_signal: SIGINT
    stop_grace_period: 60s
    networks:
      - default
    depends_on:
      - postgres
    ports:
      - '${PORT}:3000'
