version: '3.7'

services:
  postgres:
    image: sanarisan/job_sniper_postgres:1
    restart: always
    build:
      context: ./
      dockerfile: ./docker/postgres.Dockerfile
      shm_size: 512mb
    shm_size: 512mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super_secret_pWd
      POSTGRES_DB: postgres
    networks:
      - default
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    ports:
      - '5435:5432'
  app:
    image: sanarisan/job-sniper:1
    restart: always
    build:
      context: ./
      dockerfile: ./docker/app.Dockerfile
    stop_signal: SIGINT
    stop_grace_period: 60s
    networks:
      - default
    depends_on:
      - postgres
    ports:
      - '3000:3000'
